{% set name = "ros-cpp-common" %}
{% set version = "0.6.13-1" %}
{% set sha256 = "b33c02fc639806932ec27a2400f896ba379fd1efd36484f0b68cdf547d6f5649" %}

package:
  name: {{ name }}
  version: {{ version.split("-")[0] }}

source:
  url: https://github.com/ros-gbp/roscpp_core-release/archive/release/melodic/cpp_common/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make  # [unix]
  host:
    - ros-conda-mutex * melodic
    - ros-conda-base
    - python
    - catkin_pkg
    - console_bridge
    - boost-cpp 1.68.*
    - ros-catkin
  run:
    - ros-conda-mutex * melodic
    - ros-conda-base
    - console_bridge
    - boost-cpp 1.68.*

test:
  requires:
    - rospkg
  commands:
    - export ROS_ROOT=$PREFIX && python -c "import rospkg;s = rospkg.RosPack();ret = s.get_path('cpp_common');print(ret)"

about:
  home: http://www.ros.org/wiki/cpp_common
  summary: |
    cpp_common contains C++ code for doing things that are not necessarily ROS related, but are useful
  description: |
    cpp_common contains C++ code for doing things that are not necessarily ROS
    related, but are useful for multiple packages. This includes things like the
    ROS_DEPRECATED and ROS_FORCE_INLINE macros, as well as code for getting
    backtraces. This package is a component of roscpp.
  license: BSD-3-Clause
  license_file: include/ros/cpp_common_decl.h

extra:
  recipe-maintainers:
    - wolfv
    - lesteve
    - seanyen
